### ISSUE TITLE
Individual Column Filter

### ISSUE THREAD

**Issue by marcotuna** [alwint3r/sequelize-datatable-node#9]
When I try to filter/search individual column the value is not handled. It just draws the same table as if does not get any filter

For example (Data in GET/POST Request):
```
columns[4][search][value]: testColumnFilterString
columns[4][search][regex]: false
```

Javascript Function:
```
deviceTable.column(4).search("testColumnFilterString").draw();
```

**Comment by robertosousa1** [comment]
Has anyone managed to solve this problem? would be useful to me

**Comment by alwint3r** [comment]
PR #12 should fix this issue. Please re-open if the issue is still there.
